### ISSUE TITLE
Can't exclude class or function definition written in multiline with exclude_lines

### ISSUE THREAD

**Issue by khris** [coveragepy/coveragepy#894] opened 2019-12-18 09:29 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/107134/71072489-f7eb0200-21c1-11ea-8308-f6fd271c7214.png)

With `exclude_lines`, I can't exclude entire definition of class or function from coverage report, but only first line.

Here is `.coveragerc`.
```ini
[run]
include =
    sample/*

[report]
exclude_lines =
    pragma: no cover
    one_line_definition
    multi_line_definition
```

**To Reproduce**
Following is output of `coverage debug sys`
```
 (coveragetest) coveragetest   master  coverage debug sys
-- sys -------------------------------------------------------
                   version: 5.0
                  coverage: /home/*****/.virtualenvs/coveragetest/lib/python3.6/site-packages/coverage/__init__.py
                    tracer: -none-
                   CTracer: available
      plugins.file_tracers: -none-
       plugins.configurers: -none-
 plugins.context_switchers: -none-
         configs_attempted: .coveragerc
              configs_read: .coveragerc
               config_file: .coveragerc
           config_contents: '[run]\ninclude =\n    sample/*\n\n[report]\nexclude_lines =\n    pragma: no cover\n    one_line_definition\n    multi_line_definition\n'
                 data_file: -none-
                    python: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
                  platform: Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
            implementation: CPython
                executable: /home/*****/.virtualenvs/coveragetest/bin/python
              def_encoding: utf-8
               fs_encoding: utf-8
                       pid: 25933
                       cwd: /home/*****/works/coveragetest
                      path: /home/*****/.virtualenvs/coveragetest/bin
                            /usr/lib/python36.zip
                            /usr/lib/python3.6
                            /usr/lib/python3.6/lib-dynload
                            /home/*****/.virtualenvs/coveragetest/lib/python3.6/site-packages
                            /home/*****/.virtualenvs/coveragetest/lib/python3.6/site-packages/setuptools-40.8.0-py3.6.egg
                            /home/*****/.virtualenvs/coveragetest/lib/python3.6/site-packages/pip-19.0.3-py3.6.egg
               environment: VIRTUALENVWRAPPER_PYTHON = /usr/bin/python3
              command_line: /home/*****/.virtualenvs/coveragetest/bin/coverage debug sys
           sqlite3_version: 2.6.0
    sqlite3_sqlite_version: 3.22.0
```

**Expected behavior**
I know this is just regex test(+some sugar), not ast or something. Also if I attach `# pragma: no cover` to last line of class/function definition, I can exclude. but I wanna exclude multi-line definition with `exclude_lines` for convinient code exclusion management. Is there any solution?

**Comment by nedbat** [comment] 2019-12-18 11:09
I understand what you are looking for. I'm not sure how possible it is, I'll have to dig into it, but it will take some time.

**Comment by nedbat** [comment] 2019-12-18 11:10
Though, can you tell me more about how you plan to use this? I'm not sure anyone has used exclude_lines to mention specific function names. That seems kind of inconvenient. Why do you want to exclude these particular functions? Won't the list grow longer as your code grows?

**Comment by khris** [comment] 2019-12-18 23:22
Well, honestly, it's business problem, not technical one. Some Flask endpoint that not used by client should be excluded from coverage now. Of course it's not right way and I(or we) should split Flask blueprints or write tests for that endpoints far from now. But I don't want to edit source code right now.

There is no solution now, I will just use `# pragma: no cover`. And I think that(excluding specific functions/classes one by one using configuration) is not for many users. Thank you for your kindness.

**Comment by nedbat** [comment] 2021-11-15 12:22
Duplicate of #684

**Closed as completed** 2021-11-15 12:22 UTC
Labels: bug, duplicate, exclude
