### ISSUE TITLE
How to apply fail threshold to individual files?

### ISSUE THREAD

**Issue by deeplook** [coveragepy/coveragepy#1018] opened 2020-08-05 18:23 UTC
I want to make sure in my tests that some specific files have a minimum test coverage for each one individually.

I guess I think of a flag like `--fail-under`, but applied to only a set of files, individually.

Perhaps there is an alternative to inspect a standard coverage report and check for the desired files in a follow-up test which might be even ok as a workaround, but the cleaner solution appears to be a way to provide a list of input files to check the coverage for and fail if below some threshold. 

Any idea welcome...

**Comment by nedbat** [comment] 2020-08-05 22:12
There isn't a way to do this now, but perhaps this could be handled as a separate step? Export the JSON report, then produce whatever statistics you want from it.

**Comment by DeanWay** [comment] 2021-01-08 09:34
@deeplook @nedbat I wanted this functionality as well and saw this open issue and your comment about the possibility of just consuming the report, so I did just that. Made a tool for custom coverage thresholds that consumes the JSON report produced here. If anyone else wants this kind of thing check it out: https://github.com/DeanWay/coverage-threshold

**Comment by nedbat** [comment] 2021-11-03 01:28
This is a duplicate of #691.  Also, I made my own example of how to check against goals: https://nedbatchelder.com/blog/202111/coverage_goals.html

**Closed as completed by nedbat** 2021-11-03 01:28 UTC
Labels: duplicate, enhancement, target
