### ISSUE TITLE
coverage combine when combining results from different interpreter versions results in missing coverage

### ISSUE THREAD

**Issue by graingert** [coveragepy/coveragepy#1036] opened 2020-10-04 21:15 UTC
**Describe the bug**
coverage combine when combining results from different interpreter versions results in missing coverage

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.5, 3.6, 3.7, 3.8
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful. 5.3
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
1. What code are you running?  Give us a specific commit of a specific repo that we can check out. https://codecov.io/gh/twisted/ldaptor/pull/207/changes
1. What commands did you run? see https://github.com/twisted/ldaptor/pull/207/files#diff-522adf759addbd3b193c74ca85243f7dR73

**Expected behavior**
I expect to see line 40 of ldaptor/protocols/ldap/ldapconnector.py covered

**Additional context**
I'm currently trying out `tox --parallel` to save consumption of GHA parallel builds. Each build runs and then coverage combine runs at the end, as advised here https://tox.readthedocs.io/en/latest/example/basic.html#parallel-mode
see https://github.com/twisted/ldaptor/pull/207

**Comment by nedbat** [comment] 2020-10-11 15:45
I'm not sure what can be done about this.  Different versions of Python produce slightly different data when tracing the same program, because of optimizations, or because of changed decisions about what the "right" trace is.  If you measure on one version, then report using the same version, everything should make sense.  But if you measure on one version, then report using a different version, you might get results that don't seem right. 

The problem is only made more complicated when combining data from different runs.

But: you mentioned line 40 of ldapconnector.py should be covered.  This is what I see:
<img width="595" alt="image" src="https://user-images.githubusercontent.com/23789/95683108-315c8600-0bb7-11eb-84c8-2c99743af05a.png">
Coverage.py knows that the "while True" is optimized away.  This isn't an issue, since the line isn't marked as uncovered.

**Comment by graingert** [comment] 2020-10-11 16:21
@nedbat am I misinterpreting codecov here?

**Comment by nedbat** [comment] 2020-10-11 19:29
There are three possible colors for a line: green (executed), red (could have executed but didn't), and while (couldn't have executed).  Because the `while True` is optimized away, it is white.  Only the red lines are problems, not the white ones.

**Comment by graingert** [comment] 2020-10-11 19:30
ah I see, so it's the correct result for 3.8+?

**Comment by nedbat** [comment] 2020-10-11 20:14
Yes :)

**Closed as completed** 2021-11-15 12:30 UTC
Labels: bug, combine, works

**Comment by graingert** [comment] 2021-11-15 12:36
@nedbat closed as working as designed?

**Comment by nedbat** [comment] 2021-11-15 12:42
That was my interpretation of the discussion.  Was I wrong?

**Comment by graingert** [comment] 2021-11-15 12:48
> That was my interpretation of the discussion. Was I wrong?

That was my interpretation, just double checking for myself and noting for posterity
