### ISSUE TITLE
exclude_lines block exclude does not work correctly with new line def 

### ISSUE THREAD

**Issue by MalteBecker** [coveragepy/coveragepy#1472] opened 2022-10-17 13:59 UTC
**Describe the bug**
I want to exclude complete functions with the exclude_lines config parameter. The documentation says this works if i just add "def xyz". This only works if the def definition ends in the same line.

**To Reproduce**
Have "def asyncio" in your [report] exclude_lines

This will work:
```
async def asyncio(*,client: Client,) -> Optional[Union[Any, List[GltfFile]]]:
    return (
        await asyncio_detailed(
            client=client,
        )
    ).parsed
```

This will not work:
```
async def asyncio(
    *,
    client: Client,
) -> Optional[Union[Any, List[GltfFile]]]:
    return (
        await asyncio_detailed(
            client=client,
        )
    ).parsed
```

**Expected behavior**
Both versions will exclude the complete function.

**Comment by nedbat** [comment] 2022-10-18 01:25
This is a duplicate of #684.

**Closed as not planned** 2022-10-18 01:25 UTC
Labels: bug, duplicate, exclude
