### ISSUE TITLE
Report ignores decorators when run on Python 3.8 if testing was done on previous Python versions.

### ISSUE THREAD

**Issue by abompard** [coveragepy/coveragepy#941] opened 2020-02-22 14:11 UTC
**Describe the bug**
If the `coverage run` is done on Python < 3.8 and the `coverage report` is done on Python 3.8, the lines following decorators (the function/method/class definitions) will be ignored and result in lower coverage

**To Reproduce**

Here's a file to reproduce it:
```python
import unittest

class Dummy:

    @property
    def under_test(self):
        return 1

class TestDummy(unittest.TestCase):
    def test_function(self):
        obj = Dummy()
        self.assertEqual(obj.under_test, 1)

unittest.main()
```
Here's what I get when I run coverage with different Python versions:
```sh
$ .tox/py36-unittest/bin/coverage erase
$ .tox/py36-unittest/bin/coverage run --source=under_test ./under_test.py 
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
```
The test run has been done with Python 3.6. Now the report:
```sh
$ .tox/py36-unittest/bin/coverage report -m
Name            Stmts   Miss  Cover   Missing
---------------------------------------------
under_test.py       9      0   100%
```
Coverage correctly reports 100% coverage if the reporting is done with Python 3.6 (or 3.7 for that matter)
```sh
$ .tox/py38-unittest/bin/coverage report -m
Name            Stmts   Miss  Cover   Missing
---------------------------------------------
under_test.py      10      1    90%   7
```
When run with Python 3.8, `coverage report` thinks the method definition was not covered. It would behaved correctly without the decorator.

Here are the versions in both cases:
```sh
$ .tox/py36-unittest/bin/coverage --version
Coverage.py, version 5.0.3 with C extension
$ .tox/py38-unittest/bin/coverage --version
Coverage.py, version 5.0.3 with C extension
$ .tox/py36-unittest/bin/python -V
Python 3.6.10
$ .tox/py38-unittest/bin/python -V
Python 3.8.2rc1
```

I'm available if you need any more info. My use case might not even be supported, but I thought I'd report it in case it helps explain other issues.

**Comment by langmm** [comment] 2020-03-06 17:12
I just wanted to second that I am also having this issue with my project (e.g. https://codecov.io/gh/cropsinsilico/yggdrasil/src/1a39f11e62cd6924633c14caa613aae31899f9d1/yggdrasil/drivers/tests/test_CMakeModelDriver.py).

**Comment by nedbat** [comment] 2020-03-09 23:17
I'm not sure what to do about this.  Different versions of Python trace lines slightly differently.  Coverage.py "knows" what lines Python 3.7 will trace, and also what lines 3.8 will trace.

When recording execution, coverage.py just records whatever Python reports.  During the reporting phase, it takes into account the version of Python to determine what lines could have been traced but were not.  So when the measurement is on a different version than the reporting, the "could have" logic is off, and lines get incorrectly marked as missing.

(I feel like I wrote this recently on another issue, but I can't find it.)

**Comment by nedbat** [comment] 2020-03-09 23:18
Oh, this is a duplicate of #866

**Closed as completed** 2021-11-15 12:09 UTC
Labels: bug, duplicate
