### ISSUE TITLE
Condition statatement coverage

### ISSUE THREAD

**Issue by omry** [coveragepy/coveragepy#957] opened 2020-03-13 19:28 UTC
Consider:

```python
def foo(c1, c2):
    if c1 or c2:
        print("yes")
    else:
        print("no")


foo(True, False)
foo(False, False)
```

This gives 100% coverage, even with branch prediction.
```
$ coverage run --branch 1.py && coverage report
yes
no
Name    Stmts   Miss Branch BrPart  Cover
-----------------------------------------
1.py        6      0      2      0   100%
```

However, the case where c2 is True is never tested.

Thoughts?

**Comment by nedbat** [comment] 2020-03-15 11:39
This is a duplicate of #292.

**Closed as completed by nedbat** 2020-03-15 11:39 UTC
Labels: duplicate
