### ISSUE TITLE
Missing line should be considered

### ISSUE THREAD

**Issue by staticdev** [coveragepy/coveragepy#987] opened 2020-05-10 19:53 UTC
**Describe the bug**
I have a simple method that receives a list of trades (descriptions and ids) and return the id of selected ones. If none is selected, you are asked to confirm that. I've made two tests that covers the basic functionality and it says one line is missing that shouldn't.

**To Reproduce**
How can we reproduce the problem?  Please *be specific*. Don't just link to a failing CI job. Answer the questions below:
1. What version of Python are you using? 3.8.2.
1. What version of coverage.py are you using? The output of `coverage debug sys` is helpful.
```
-- sys -------------------------------------------------------
                        version: 5.0.3
                       coverage: /home/static/.local/lib/python3.8/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                                 setup.cfg
                                 tox.ini
                                 pyproject.toml
                   configs_read: -none-
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
                       platform: Linux-5.4.0-29-generic-x86_64-with-glibc2.29
                 implementation: CPython
                     executable: /usr/bin/python3
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 23395
                            cwd: /home/static/workspace/stackoverflow
                           path: /home/static/.local/bin
                                 /usr/lib/python38.zip
                                 /usr/lib/python3.8
                                 /usr/lib/python3.8/lib-dynload
                                 /home/static/.local/lib/python3.8/site-packages
                                 /usr/local/lib/python3.8/dist-packages
                                 /usr/lib/python3/dist-packages
                    environment: PYENV_SHELL = bash
                                 PYENV_VIRTUALENV_INIT = 1
                   command_line: /home/static/.local/bin/coverage debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.31.1
        sqlite3_compile_options: COMPILER=gcc-9.3.0
                                 ENABLE_COLUMN_METADATA
                                 ENABLE_DBSTAT_VTAB
                                 ENABLE_FTS3
                                 ENABLE_FTS3_PARENTHESIS
                                 ENABLE_FTS3_TOKENIZER
                                 ENABLE_FTS4
                                 ENABLE_FTS5
                                 ENABLE_JSON1
                                 ENABLE_LOAD_EXTENSION
                                 ENABLE_PREUPDATE_HOOK
                                 ENABLE_RTREE
                                 ENABLE_SESSION
                                 ENABLE_STMTVTAB
                                 ENABLE_UNLOCK_NOTIFY
                                 ENABLE_UPDATE_DELETE_LIMIT
                                 HAVE_ISNAN
                                 LIKE_DOESNT_MATCH_BLOBS
                                 MAX_SCHEMA_RETRY=25
                                 MAX_VARIABLE_NUMBER=250000
                                 OMIT_LOOKASIDE
                                 SECURE_DELETE
                                 SOUNDEX
                                 TEMP_STORE=1
                                 THREADSAFE=1
                                 USE_URI
```
1. What versions of what packages do you have installed? The output of `pip freeze` is helpful.
```
alabaster==0.7.12
appdirs==1.4.3
argcomplete==1.11.1
argh==0.26.2
astroid==2.3.3
attrs==19.3.0
Babel==2.8.0
blessings==1.7
certifi==2020.4.5.1
cfgv==3.1.0
chardet==3.0.4
click==7.1.1
codecov==2.0.15
colorlog==4.1.0
coverage==5.0.3
decorator==4.4.1
distlib==0.3.0
docutils==0.16
filelock==3.0.12
grpc-tools==0.0.1
grpcio==1.27.2
grpcio-tools==1.27.2
identify==1.4.15
idna==2.9
imagesize==1.2.0
importlab==0.5.1
inquirer==2.6.3
isort==4.3.21
Jinja2==2.11.2
lazy-object-proxy==1.4.3
livereload==2.6.1
MarkupSafe==1.1.1
mccabe==0.6.1
more-itertools==8.2.0
networkx==2.4
ninja==1.9.0.post1
nodeenv==1.3.5
nox==2019.11.9
numpy==1.18.2
packaging==20.3
pandas==1.0.3
pathtools==0.1.2
pluggy==0.13.1
port-for==0.3.1
pre-commit==2.3.0
protobuf==3.11.3
py==1.8.1
pycodestyle==2.5.0
Pygments==2.6.1
pylint==2.4.4
pyparsing==2.4.7
pytest==5.4.2
pytest-mock==3.0.0
python-dateutil==2.8.1
python-editor==1.0.4
pytz==2019.3
PyYAML==5.3.1
readchar==2.0.1
requests==2.23.0
rope==0.16.0
rstcheck==3.3.1
six==1.14.0
snowballstemmer==2.0.0
Sphinx==3.0.3
sphinx-autobuild==0.7.1
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
toml==0.10.0
tomlkit==0.5.11
tornado==6.0.4
typed-ast==1.4.1
urllib3==1.25.9
virtualenv==20.0.20
watchdog==0.10.2
wcwidth==0.1.9
wrapt==1.11.2
xlrd==1.2.0
```
1. What code are you running?  Give us a specific commit of a specific repo that we can check out.
```python
# question.py
from typing import List, Tuple
import inquirer

def select_trades(trades: List[Tuple[str, int]]) -> List[int]:
    while True:
        selection = inquirer.prompt(
            [
                inquirer.Checkbox(
                    "trades",
                    message=(
                        "Select auction trades? "
                        "(press space to select and enter to finish)"
                    ),
                    choices=trades,
                )
            ]
        )["trades"]
        if len(selection) == 0:
            answer = inquirer.prompt(
                [
                    inquirer.List(
                        "",
                        message="No trade selected.\nDo you confirm?",
                        choices=["Yes", "No"],
                    )
                ]
            )[""]
            if answer == "Yes":
                return []
        else:
            break
    return selection
```
Test code:
```python
# test_problem.py
from unittest.mock import patch

from problem import select_trades

@patch(
    "inquirer.prompt",
    side_effect=[{"trades": []}, {"": "No"}, {"trades": []}, {"": "Yes"}],
)
def test_select_trades_empty(mock_inquirer_prompt) -> None:
    trades = [("trade 1", 0), ("trade 2", 1)]
    assert select_trades(trades) == []


@patch("inquirer.prompt", return_value={"trades": [1]})
def test_select_trades_some_selected(mock_inquirer_prompt) -> None:
    trades = [("trade 1", 0), ("trade 2", 1)]
    assert select_trades(trades) == [1]
```

1. What commands did you run?
```
coverage run --source=. -m pytest
coverage report
coverage html
```

**Expected behavior**
100% test coverage.

**Additional context**
For some reason, coverage is saying that the `break` like is not covered, but in the second test case, the `while True` breaks and return the expected value for the test.

**Comment by nedbat** [comment] 2020-05-10 20:17
Thanks for the details, it really helps to understand what you are seeing.

This is a duplicate of #198, though with a break instead of a continue.  Python optimizes away jumps to jumps, so the break line is never executed directly.

Here's a simpler reproduction:
```
def func():
    x = 12
    while True:
        if x < 20:
            print("Hello")
            x = 30
        else:
            break   # line 8
    return x

print(func())
```
Line 8 is marked as not executed.  You can see why when you disassemble the compiled byte code:
```
Disassembly of <code object func at 0x10ef04be0, file "foo.py", line 1>:
  2           0 LOAD_CONST               1 (12)
              2 STORE_FAST               0 (x)

  4     >>    4 LOAD_FAST                0 (x)
              6 LOAD_CONST               2 (20)
              8 COMPARE_OP               0 (<)
             10 POP_JUMP_IF_FALSE       30

  5          12 LOAD_GLOBAL              0 (print)
             14 LOAD_CONST               3 ('Hello')
             16 CALL_FUNCTION            1
             18 POP_TOP

  6          20 LOAD_CONST               4 (30)
             22 STORE_FAST               0 (x)
             24 JUMP_ABSOLUTE            4

  8          26 JUMP_ABSOLUTE           30
             28 JUMP_ABSOLUTE            4

  9     >>   30 LOAD_FAST                0 (x)
             32 RETURN_VALUE
```
Line 4, performs the "if x < 20" check, and if it is false, jumps to byte code offset 30, which is the "return x".  Line 8 is in the byte code, but nothing can ever reach it.

**Closed as completed by nedbat** 2020-05-10 20:17 UTC
Labels: bug, duplicate
