### ISSUE TITLE
Add skip_covered to [html] config

### ISSUE THREAD

**Issue by ryboe** [coveragepy/coveragepy#1098] opened 2021-01-10 20:11 UTC
**Is your feature request related to a problem? Please describe.**
We can set `skip_covered = true` in the `[report]` section of a config file, but the setting is strangely missing from `[html]`.

```
Unrecognized option '[tool.coverage.html] skip_covered=' in config file pyproject.toml
```

Instead, I have to pass it as a flag.

```sh
coverage html --skip-covered
```

**Describe the solution you'd like**
I'd like to be able to write this in `pyproject.toml`.
```toml
[tool.coverage.html]
skip_covered = true
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nedbat** [comment] 2021-01-10 20:31
Duplicate of #1090.  Something is in the air....

**Closed as completed by nedbat** 2021-01-10 20:31 UTC
Labels: duplicate, enhancement
