### ISSUE TITLE
Allow to give fail_under as absolute number of uncovered lines

### ISSUE THREAD

**Issue by MaartenGrothus** [coveragepy/coveragepy#1290] opened 2021-12-11 03:32 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use coverage.py to ensure my code coverage is not decreasing. However, if my code base is growing, and the new code has a test coverage that is higher of the legacy code, I can actually insert a significant amount of uncovered code without failing. This is due to the fact that in percent, the coverage has not declined.

This is even more prominent if I am not adjusting the coverage threshold frequently.

**Describe the solution you'd like**
I would like to have an additional parameter `fail-uncovered-over`, which allows to specify a maximum count of uncovered lines. This would in practice enforce a coverage of 100 % for code which is completely new.

**Comment by nedbat** [comment] 2021-12-12 00:01
This is a duplicate of #815.

**Closed as completed by nedbat** 2021-12-12 00:01 UTC
Labels: duplicate, enhancement, target
