### ISSUE TITLE
Coverage.py misses lines in Python 3.11

### ISSUE THREAD

**Issue by Gerhut** [coveragepy/coveragepy#1911] opened 2024-12-31 08:48 UTC
**Describe the bug**
We recently found that coverage.py misses lines after Sanic test client calls in Python 3.11, and it's resolved after upgrading to Python 3.12.

**To Reproduce**

requirements.txt

```
coverage==7.6.10
pytest==8.3.4
sanic==24.6.0
sanic-testing==24.6.0
```

test_app.py

```python
def test_app():
    from sanic import Sanic

    app = Sanic(__name__)

    app.config.TOUCHUP = False

    client = app.test_client
    _, response = client.get("/")
    assert response is not None
    assert response.status == 500
```

Run in Python 3.11.9

```
$ python3.11 -m coverage run -m pytest
python3.11 -m coverage run -m pytest
===================================== test session starts ======================================
platform linux -- Python 3.11.9, pytest-8.3.4, pluggy-1.5.0
rootdir: /workspaces/sanic-coverage-issue
plugins: anyio-4.7.0
collected 1 item                                                                               

test_app.py .                                                                            [100%]

================================ 1 passed, 3 warnings in 0.38s =================================

$ python3.11 -m coverage report -m
Name          Stmts   Miss  Cover   Missing
-------------------------------------------
test_app.py       8      2    75%   10-11
-------------------------------------------
TOTAL             8      2    75%
```

Run in Python 3.12.1

```
$ python3.12 -m coverage run -m pytest
===================================== test session starts ======================================
platform linux -- Python 3.12.1, pytest-8.3.4, pluggy-1.5.0
rootdir: /workspaces/sanic-coverage-issue
plugins: anyio-4.7.0
collected 1 item                                                                               

test_app.py .                                                                            [100%]
================================ 1 passed, 3 warnings in 0.84s =================================

$ python3.12 -m coverage report -m
Name          Stmts   Miss  Cover   Missing
-------------------------------------------
test_app.py       8      0   100%
-------------------------------------------
TOTAL             8      0   100%
```

**Expected behavior**
All lines are supposed to be covered even in Python 3.11

**Additional context**
I will try more python versions when I get some more time.

---

3.11.11 bad
3.12.0 good

**Comment by nedbat** [comment] 2024-12-31 15:46
This seems like a duplicate of #1595.  There's something about some kind of async operations that aren't properly traced in 3.11, but are in 3.12.

**Closed as completed by nedbat** 2024-12-31 15:46 UTC
Labels: bug, duplicate
