### ISSUE TITLE
On Python >= 3.7 running on any OS (Win, macOS, Linux), coverage raises ModuleNotFoundError

### ISSUE THREAD

**Issue by tysonite** [coveragepy/coveragepy#968] opened 2020-04-01 16:11 UTC
"import" statement fails with ModuleNotFoundError if running `coverage run` using Python >= 3.7 on any OS. It works correctly without coverage tool, or with coverage tool using Python <= 3.6.

Coverage version is 5.0.4.

This [repo/commit](https://github.com/tysonite/robotframework/commit/f044b786ed8345732244e8988197daab2cd360ef) contains faulty scenario. In order to reproduce, clone it and run following commands from the source root directory:
- `python3.7 -m pip install -r atest/requirements.txt`
- `python3.7 -m pip install coverage`
- `python3.7 atest/run.py "python3.7 -m coverage run --branch --append" --exclude no-ci atest/robot/core/filter_by_names.robot`

After that, console output shall have test failures.

Note that there are 2 Python interpreters in the last command line above, if you change 2nd one to `python3.6` with (or without) coverage, there will be NO failures in the console output.
E.g.
1. `python3.7 atest/run.py "python3.6 -m coverage run --branch --append" --exclude no-ci atest/robot/core/filter_by_names.robot`
1. `python3.7 atest/run.py python3.6 --exclude no-ci atest/robot/core/filter_by_names.robot`
1. `python3.7 atest/run.py python3.7 --exclude no-ci atest/robot/core/filter_by_names.robot`

Additional info:
```
$ python3.7 -m coverage debug sys
-- sys -------------------------------------------------------
                        version: 5.0.4
                       coverage: /home/tysonite/.local/lib/python3.7/site-packages/coverage/__init__.py
                         tracer: -none-
                        CTracer: available
           plugins.file_tracers: -none-
            plugins.configurers: -none-
      plugins.context_switchers: -none-
              configs_attempted: .coveragerc
                                 setup.cfg
                                 tox.ini
                                 pyproject.toml
                   configs_read: -none-
                    config_file: None
                config_contents: -none-
                      data_file: -none-
                         python: 3.7.5 (default, Nov  7 2019, 10:50:52) [GCC 8.3.0]
                       platform: Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic
                 implementation: CPython
                     executable: /usr/bin/python3.7
                   def_encoding: utf-8
                    fs_encoding: utf-8
                            pid: 8083
                            cwd: /home/tysonite/robotframework
                           path: /home/tysonite/robotframework
                                 /usr/lib/python37.zip
                                 /usr/lib/python3.7
                                 /usr/lib/python3.7/lib-dynload
                                 /home/tysonite/.local/lib/python3.7/site-packages
                                 /usr/local/lib/python3.7/dist-packages
                                 /usr/lib/python3/dist-packages
                    environment: -none-
                   command_line: /home/tysonite/.local/lib/python3.7/site-packages/coverage/__main__.py debug sys
                sqlite3_version: 2.6.0
         sqlite3_sqlite_version: 3.22.0
             sqlite3_temp_store: 0
        sqlite3_compile_options: COMPILER=gcc-7.4.0
                                 ENABLE_COLUMN_METADATA
                                 ENABLE_DBSTAT_VTAB
                                 ENABLE_FTS3
                                 ENABLE_FTS3_PARENTHESIS
                                 ENABLE_FTS3_TOKENIZER
                                 ENABLE_FTS4
                                 ENABLE_FTS5
                                 ENABLE_JSON1
                                 ENABLE_LOAD_EXTENSION
                                 ENABLE_PREUPDATE_HOOK
                                 ENABLE_RTREE
                                 ENABLE_SESSION
                                 ENABLE_STMTVTAB
                                 ENABLE_UNLOCK_NOTIFY
                                 ENABLE_UPDATE_DELETE_LIMIT
                                 HAVE_ISNAN
                                 LIKE_DOESNT_MATCH_BLOBS
                                 MAX_SCHEMA_RETRY=25
                                 MAX_VARIABLE_NUMBER=250000
                                 OMIT_LOOKASIDE
                                 SECURE_DELETE
                                 SOUNDEX
                                 TEMP_STORE=1
                                 THREADSAFE=1
```

```
$ python3.7 -m pip freeze
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
blinker==1.4
certifi==2018.1.18
chardet==3.0.4
click==6.7
cloud-init==19.4
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
coverage==5.0.4
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
docutils==0.16
httplib2==0.9.2
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
lxml==4.5.0
MarkupSafe==1.0
netifaces==0.10.4
oauthlib==2.0.6
PAM==0.4.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
Pygments==2.6.1
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==17.5.0
pyserial==3.4
python-apt==1.6.5+ubuntu0.2
python-debian==0.1.32
pyxdg==0.25
PyYAML==5.3.1
requests==2.18.4
requests-unixsocket==0.1.5
SecretStorage==2.3.1
service-identity==16.0.0
six==1.11.0
ssh-import-id==5.7
systemd-python==234
Twisted==17.9.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
zope.interface==4.3.2
```

This [GH run](https://github.com/tysonite/robotframework/actions/runs/67743858) gives more background on failed cases.

**Comment by tysonite** [comment] 2020-04-01 17:33
It looks like that if Coverage version < 5.0, this issue does not happen. E.g. this [run](https://github.com/tysonite/robotframework/runs/552581472?check_suite_focus=true) has been successful.

**Comment by pekkaklarck** [comment] 2020-04-01 22:22
If I understand this correctly, on Robot Framework side this happens in this code:

```python
if 'robot' not in sys.modules and __name__ == '__main__':
    import pythonpathsetter
```

When executing the framework normally, the condition isn't true (`robot` is in `sys.modules`) and the import isn't done. Somehow the condition now seems to be true in this particular case.

**Comment by nedbat** [comment] 2020-04-11 20:56
I suspect this has something to do with the changes in sys.path and perhaps __file__.  But I don't understand the Robot Framework code well enough to isolate where it is going wrong.  Can you find a smaller reproduction to debug with?

**Comment by tysonite** [comment] 2020-05-09 10:33
The minimal example is like that:

```
import sys

# Allows running as a script. __name__ check needed with multiprocessing:
# https://github.com/robotframework/robotframework/issues/1137
if 'robot' not in sys.modules and __name__ == '__main__':
    import pythonpathsetter
```

Create a Python source file with content above in `src/robot`, and run:
* `python3.7 -m coverage run --branch --append src/robot/file.py` - NOK
* `python3.7  src/robot/file.py` - OK

The NOK error output looks like:
```
Traceback (most recent call last):
  File "src/robot/file.py", line 6, in <module>
    import pythonpathsetter
ModuleNotFoundError: No module named 'pythonpathsetter'
```

This also happens with coverage 5.1.

**Comment by nedbat** [comment] 2020-05-09 12:49
@tysonite I appreciate the code example.  Can you be more specific? Starting with a fresh Python 3.7 virtualenv, what do I need to install?  What repo do I need to clone, at what commit? What is "pythonpathsetter"? Where would that have come from?

**Comment by tysonite** [comment] 2020-05-09 13:43
Sorry for confusions. I do following:
* `git clone https://github.com/tysonite/robotframework.git`
* `python3.7 -m venv .p37_venv`
* `source .p37_venv/bin/activate`
* `cd robotframework`
* Create `src/robot/file.py` and write above content into it
* `pip install coverage`
* `python3.7 -m coverage run --branch --append src/robot/file.py` - NOK
* `python3.7 src/robot/file.py` - OK

`pythonpathsetter` is a Python file located in `src/robot` directory of the cloned repo. 

If you replace `python3.7` with, for example, `python3.6` - both commands are OK.

**Comment by nedbat** [comment] 2020-05-10 20:36
Thanks, this is a duplicate of #919, but I'm not sure it will be possible to fix it.

**Closed as completed** 2020-05-10 20:36 UTC
Labels: bug, duplicate

**Comment by nedbat** [comment] 2020-05-10 21:03
As a work-around, instead of this:
```
python3.7 -m coverage run --branch --append src/robot/file.py
```
use this:
```
coverage run --branch --append src/robot/file.py
```

**Comment by owillebo** [comment] 2020-11-11 11:08
I confirm this issue.
Running with 2 files in the same folder. An empty bar.py and foo.py holding;

      from sys import path
      print(path[0])
      import bar

The following session reveals the issue;

      C:\projects\coverage_issue>python --version
      Python 3.7.9

      C:\projects\coverage_issue>coverage --version
      Coverage.py, version 5.3 with C extension
      Full documentation is at https://coverage.readthedocs.io

      C:\projects\coverage_issue>python C:\projects\coverage_issue\foo.py
      C:\projects\coverage_issue

      C:\projects\coverage_issue>coverage run C:\projects\coverage_issue\foo.py
      C:\projects\coverage_issue

      C:\projects\coverage_issue>python -m coverage run C:\projects\coverage_issue\foo.py
      C:\projects\coverage_issue

      C:\projects\coverage_issue>CD ..

      C:\projects>python C:\projects\coverage_issue\foo.py
      C:\projects\coverage_issue

      C:\projects>coverage run C:\projects\coverage_issue\foo.py
      C:\projects\coverage_issue

      C:\projects>python -m coverage run C:\projects\coverage_issue\foo.py
      C:\projects
      Traceback (most recent call last):
        File "C:\projects\coverage_issue\foo.py", line 3, in <module>
          import bar
      ModuleNotFoundError: No module named 'bar'
