### ISSUE TITLE
Function is not excluded from the report even though it is specified

### ISSUE THREAD

**Issue by Junkkk** [coveragepy/coveragepy#1694] opened 2023-10-24 22:35 UTC
**Describe the bug**
Function is not excluded from the report even though it is specified

**To Reproduce**
Python 3.10.11
coverage_version: 7.3.2

i got func like that
```python
def some(
    a: int
):
    print(f"{a} rly?")
    return a + 1
```
and in my pyproject.toml
[tool.coverage.report]
exclude_also = ["def some"]

After testing, report mark this function as untested.

**Expected behavior**
After testing, this function mark as tested

**Additional context**
But if i use 
```python
def some(a: int):
    print(f"{a} rly?")
    return a + 1
```
everything is ok

**Comment by nedbat** [comment] 2023-10-25 01:07
This is a duplicate of #684.

**Closed as not planned by nedbat** 2023-10-25 01:07 UTC
Labels: bug, duplicate
